In [1]:
import numpy as np
import matplotlib.pyplot as plt

G = 6.6743E-11

In [2]:
def findAcceleration(N, r, m):
    a = np.zeros((N, 3))
    for i in range(len(m)):
        for j in range(N):
            if (i != j):
                a[i] = G*m[i]*m[j]*(r[j] - r[i]) / np.linalg.norm(r[j] - r[i])**3
    return a

# def getDistance(x_body1, x_body2):
#     for () in x:
        
#     return abs(y - x)

def f_true(r, v, m, t, delta_t):
    N = 3
    acceleration_vec = findAcceleration(N, r, m)
    u_dot_r = v
    u_dot_v = acceleration_vec
    return u_dot_r, u_dot_v

def RK4(r, v, m, t, delta_t):
    k1_r, k1_v = f_true(r, v, m, t, delta_t)
    k2_r, k2_v = f_true(r + 0.5*delta_t*k1_r, v + 0.5*delta_t*k1_v, m, t + 0.5*delta_t, delta_t)
    k3_r, k3_v = f_true(r + 0.5*delta_t*k2_r, v + 0.5*delta_t*k2_v, m, t + 0.5*delta_t, delta_t)
    k4_r, k4_v = f_true(r + delta_t*k3_r, v + delta_t*k3_v, m, t + delta_t, delta_t)
    return r + (delta_t / 6) * (k1_r + 2*k2_r + 2*k3_r + k4_r), v + (delta_t / 6) * (k1_v + 2*k2_v + 2*k3_v + k4_v)

m_vec = np.array([1.9891*10**30, 6.39*10**23, 10.6*10**15])      # sun, mars, phobos

x_sun = np.array([0, 0, 0])
x_mars = np.array([-1.452225829003665E+08, 1.982282617940946E+08, 7.716734755059928E+06])
x_phobos = np.array([-1.452162997749086E+08, 1.982346674348103E+08, 7.713809702492163E+06])
x_vec = np.array([x_sun, x_mars, x_phobos])

v_sun = np.array([0, 0, 0])
v_mars = np.array([-1.863015592458860E+01,-1.225724886921267E+01, 2.001015393882497E-01])
v_phobos = np.array([-1.989472584067270E+01, -1.072067660202062E+01, 9.414140308600949E-01])
v_vec = np.array([v_sun, v_mars, v_phobos])   
                                 
N_body = 3

In [3]:
print(findAcceleration(N_body, x_vec, m_vec))

[[-1.37515286e+19  1.87722019e+19  7.30473609e+17]
 [ 3.37925910e+21  3.44515159e+21 -1.57318369e+21]
 [-3.37925910e+21 -3.44515159e+21  1.57318369e+21]]


In [4]:
print(f_true(x_vec, v_vec, m_vec, t = 10, delta_t = 0.1))

print(RK4(x_vec, v_vec, m_vec, t = 10, delta_t = 0.1))

(array([[  0.        ,   0.        ,   0.        ],
       [-18.63015592, -12.25724887,   0.20010154],
       [-19.89472584, -10.7206766 ,   0.94141403]]), array([[-1.37515286e+19,  1.87722019e+19,  7.30473609e+17],
       [ 3.37925910e+21,  3.44515159e+21, -1.57318369e+21],
       [-3.37925910e+21, -3.44515159e+21,  1.57318369e+21]]))
(array([[-4.58384287e+16,  6.25740061e+16,  2.43491203e+15],
       [ 1.12641429e+19,  1.14839101e+19, -5.24391361e+18],
       [-1.12641429e+19, -1.14839101e+19,  5.24391361e+18]]), array([[-6.87576431e+17,  9.38610091e+17,  3.65236805e+16],
       [ 1.68961873e+20,  1.72259009e+20, -7.86585441e+19],
       [-1.68961873e+20, -1.72259009e+20,  7.86585441e+19]]))


In [ ]:
fig = plt.figure(figsize=(4,4))
for t in range(0, 30000000, 3000000):
  r_new, v_new = RK4(x_vec, v_vec, m_vec, t, delta_t = 3000000)
  ax = fig.add_subplot(111, projection='3d')
  ax.scatter(r_new[0], r_new[1], r_new[2])
  print(r_new)
plt.show()